name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # spec: cypress/e2e/**/*.js

      - name: Generate HTML Report
        if: always() # Run even if tests fail
        run: node report.js

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: cypress/reports/